### ISSUE TITLE
Getting error when attempting to look up wiki article

### ISSUE THREAD

**Issue by mayersj1** [jozefg/wiki-summary.el#2]
Using the latest version of wiki-summary, when I attempt to search for an article, I get the following error:

error in process filter: JSON readtable error

Not sure if it's an issue with a proxy (I'm behind a proxy) or not. Is there any way to get more info regarding this error?

**Comment by jozefg** [comment]
Interesting. I can't reproduce this so would you mind running the following snippet

```
(switch-to-buffer
  (url-retrieve-synchronously (wiki-summary/make-api-query "Emacs")))
```

For me this brings up a buffer with some headers and then the JSON response. If you don't see that then it's likely something with how your proxy and `url` are interacting. If not it's my fault :)

**Comment by mayersj1** [comment]
Okay, so definitely an issue with the proxy. Getting this message: " The SSL handshake could not be performed."

Here's what I'm setting for the proxy info (proxy host info has been changed):

(with-temp-buffer
        (cond ((eq (call-process "ping" nil (current-buffer) nil "-c" "1" "-t" "2" "-q" "my-proxy.mydomain.com") 0)
               (setq url-proxy-services '(("no_proxy" . "mydomain\.com")
                                          ("http" . "my-proxy.mydomain.com:80")
                                          ("https" . "my-proxy.mydomain.com:80")
                                          ("ftp" . "my-proxy.mydomain.com:80"))))))

These settings work for grabbing packages from Melpa and such as well as allowing elfeed to grab news feeds. Is there something else that I should be configuring to work with wiki-summary?

**Comment by jozefg** [comment]
Huh okay. Judging by the SSL error you're being bitten by the fact that wiki-summary uses the https version of the Wikipedia API. The hacky fix would be to redefine `make-api-query` as

``` elisp
(defun wiki-summary/make-api-query (s)
  (let ((pre "http://en.wikipedia.org/w/api.php?continue=&action=query&titles=")
        (post "&prop=extracts&exintro=&explaintext=&format=json&redirects")
        (term (url-hexify-string (replace-regexp-in-string " " "_" s))))
```

Which is just a one character difference. If this fixes it I'll add a configuration variable which lets you decide whether or not to use https. I don't know url well enough to guess the underlying issue with your proxy though :/
