### ISSUE TITLE
Open in a editable buffer

### ISSUE THREAD

**Issue by andrewsanchez** [jozefg/wiki-summary.el#4]
Is it possible to display the wiki summary in a buffer that can be edited directly?  Even better - automatically put the wiki summary into an org buffer.  Then one could edit the text in org and refile it to the desired location.  I plan on using this not only to look up a wiki summary, but to manipulate the wiki summary and integrate into my notes, which I maintain in org files, for reference and study purposes.  Brilliant mode - thanks so much!

**Comment by ayman** [comment]
Would you want a new buffer or rather a `wiki-summary-insert` function?

**Comment by andrewsanchez** [comment]
If I had to choose one over the other, I would take the insert function,
but both options would probably come in handy.

On Sun, Jul 3, 2016 at 12:23 AM, ayman notifications@github.com wrote:

> Would you want a new buffer or rather a wiki-summary-insert function?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jozefg/wiki-summary.el/issues/4#issuecomment-230139728,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALKp6hPQ1rMS2Kd3BFCwju5t6iC9t_o8ks5qR2NUgaJpZM4HrcGn
> .

## 

With Love,
Andrew

_"A little learning is a dang'rous thing;Drink deep, or taste not the
Pierian spring"_

**Comment by ayman** [comment]
I issued a Pull Request for the insert function. BTW @andrewsanchez You can just call `M-x read-only-mode` to toggle the buffer to writeable if you need that.
